import { Request, Response } from 'express';
import QuestionPaper from '../models/QuestionPaper';
import Question from '../models/Question';
import mongoose from 'mongoose';

// @desc    Get all question papers
// @route   GET /api/papers
// @access  Private
export const getPapers = async (req: Request, res: Response): Promise<void> => {
  try {
    const papers = await QuestionPaper.find({})
      .populate('subjectId', 'name code')
      .populate('createdBy', 'name email');
    res.json(papers);
  } catch (error) {
    res.status(500).json({ message: 'Server error pulling papers' });
  }
};

// @desc    Get single question paper by ID
// @route   GET /api/papers/:id
// @access  Private
export const getPaperById = async (req: Request, res: Response): Promise<void> => {
  try {
    const paper = await QuestionPaper.findById(req.params.id)
      .populate('subjectId', 'name code')
      .populate('createdBy', 'name email')
      .populate('questions');
    
    if (!paper) {
      res.status(404).json({ message: 'Paper not found' });
      return;
    }
    
    res.json(paper);
  } catch (error) {
    res.status(500).json({ message: 'Server error pulling paper' });
  }
};

// Helper: Shuffle array
const shuffleArray = (array: any[]) => {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
};

// Helper: DP to find subset summing to target
const findSubsetWithExactSum = (questions: any[], targetSum: number): any[] | null => {
  if (targetSum === 0) return [];
  const dp: number[][] | null[] = new Array(targetSum + 1).fill(null);
  dp[0] = [];
  
  for (let i = 0; i < questions.length; i++) {
    const marks = questions[i].marks;
    for (let j = targetSum; j >= marks; j--) {
      if (dp[j - marks] !== null && dp[j] === null) {
        dp[j] = [...(dp[j - marks] as number[]), i];
      }
    }
    if (dp[targetSum] !== null) {
       return (dp[targetSum] as number[]).map(idx => questions[idx]);
    }
  }
  return null;
};

// @desc    Auto Generate a Question Paper
// @route   POST /api/papers/generate
// @access  Private (Teacher/Admin only)
  export const generatePaper = async (req: Request, res: Response): Promise<void> => {
    try {
      const { title, subjectId, batchId, topics, totalMarks, durationMinutes, distribution } = req.body;
      // distribution expected: { Easy: percentage, Medium: percentage, Hard: percentage }
      
      if (!subjectId || !batchId) {
        res.status(400).json({ message: 'Subject ID and Target Batch ID are strictly required' });
        return;
      }

    // Default distribution if none provided
    const dist = distribution || { Easy: 30, Medium: 50, Hard: 20 };
    
    // Calculate exact target marks per difficulty
    const targetEasy = Math.round((dist.Easy / 100) * totalMarks);
    const targetHard = Math.round((dist.Hard / 100) * totalMarks);
    const targetMedium = totalMarks - targetEasy - targetHard; // Ensures exact sum

    const query: any = { subjectId, batchId, status: 'Approved' };
    if (topics && topics.length > 0) {
      query.topicId = { $in: topics };
    }

    const availableQuestions = await Question.find(query);
    const easyQs = shuffleArray(availableQuestions.filter(q => q.difficulty === 'Easy'));
    const medQs = shuffleArray(availableQuestions.filter(q => q.difficulty === 'Medium'));
    const hardQs = shuffleArray(availableQuestions.filter(q => q.difficulty === 'Hard'));

    const selectedEasy = findSubsetWithExactSum(easyQs, targetEasy);
    if (!selectedEasy && targetEasy > 0) {
       res.status(400).json({ message: `Insufficient Approved Easy questions to form exactly ${targetEasy} marks.` });
       return;
    }

    const selectedMed = findSubsetWithExactSum(medQs, targetMedium);
    if (!selectedMed && targetMedium > 0) {
       res.status(400).json({ message: `Insufficient Approved Medium questions to form exactly ${targetMedium} marks.` });
       return;
    }

    const selectedHard = findSubsetWithExactSum(hardQs, targetHard);
    if (!selectedHard && targetHard > 0) {
       res.status(400).json({ message: `Insufficient Approved Hard questions to form exactly ${targetHard} marks.` });
       return;
    }

    const finalQuestions = [...(selectedEasy || []), ...(selectedMed || []), ...(selectedHard || [])];

    const paper = await QuestionPaper.create({
      title,
      subjectId,
      totalMarks,
      durationMinutes,
      questions: finalQuestions.map(q => q._id),
      createdBy: (req.user as any)?._id,
      status: 'Draft',
      isAutoGenerated: true
    });

    res.status(201).json(paper);
  } catch (error: any) {
    console.error("Paper Generation Error:", error);
    res.status(500).json({ message: 'Server Error generating paper', error: error.message });
  }
};
